on:
  push:
    branches:
      - master

    paths:
      - gas/**.js
      - .github/workflows/gas.yml

env:
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
  DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

defaults:
  run:
    working-directory: gas

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
      - run: echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json
      - run: npm install --global clasp
      - run: npx clasp push
      - run: npx clasp deploy -i $DEPLOYMENT_ID

